/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2018-04-25 09:13:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import education.saipali.UserDao;
import education.saipali.User;

public final class editform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Edit User</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("        <!--Be sure to include popper.min.js before Bootstrapâs JavaScript-->\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/popper.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


String id = request.getParameter("id");
User u = UserDao.getRecordById(Integer.parseInt(id));


      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row mt-5\">\r\n");
      out.write("<h1 class=\"text-dark\">Edit Form</h1>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<form method=\"post\" action=\"edituser.jsp\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"id\" value=\"");
      out.print( u.getId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<table class=\"table table-hover\">\r\n");
      out.write("<tr><td>Name</td><td><div class=\"form-group\"><input class=\"form-control\" type=\"text\" name=\"name\" value=\"");
      out.print( u.getName());
      out.write("\"></div></td></tr>\r\n");
      out.write("<tr><td>Password</td><td><div class=\"form-group\"><input type=\"password\" name=\"password\" value=\"");
      out.print( u.getPassword());
      out.write("\"></div></td></tr>\r\n");
      out.write("<tr><td>Email</td><td><div class=\"form-group\"><input type=\"email\" name=\"email\" value=\"");
      out.print( u.getEmail());
      out.write("\"></div></td></tr>\r\n");
      out.write("<tr><td>Sex</td><td><div class=\"form-group\"><input type=\"radio\" name=\"sex\" value=\"M\">Male<input type=\"radio\" name=\"sex\" value=\"F\">Female</div></td></tr>\r\n");
      out.write("<tr><td>Country</td><td><select class=\"form-control\" name=\"country\" style=\"width:155px;\">\r\n");
      out.write("<option>India</option>\r\n");
      out.write("<option>Pakistan</option>\r\n");
      out.write("<option>Afghanistan</option>\r\n");
      out.write("<option>Uganda</option>\r\n");
      out.write("<option>Kenya</option>\r\n");
      out.write("<option>Japan</option>\r\n");
      out.write("<option>Other</option>\r\n");
      out.write("</select></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<td colspan=\"2\"><input type=\"submit\" class=\"btn btn-outline-primary\" value=\"Edit User\"></td>\r\n");
      out.write("</div>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
